version: 2.1
      
jobs:
#Next Job will call the command to print circle workflow ID
  failed-job:
    steps:
      - run: exit 1
      - run:
          name: on error
          command: echo "Hello error"
          when: on_fail

workflows:
  my_workflow:
    jobs:
      - failed-job